Feat: User, Dog, Home 엔티티 생성
coding-union-kr/haru-puppy pull request #15
Opened 2023-12-11 11:26 UTC by senique-dev

## ✅ Changes Made
- User, Dog, Home 엔티티 생성

## 🙋🏻‍ Review Point
- 리뷰어가 확인해야 할 사항 코멘트

## 📸 Screenshot
> 스크린 샷 첨부(테스트, DB 화면 캡쳐 등)
![스크린샷 2023-12-11 오후 6 57 02](https://github.com/coding-union-kr/haru-puppy/assets/127134472/0d38cbe0-5360-4e6f-8596-1f3f2bdc07d2)

## 🙋🏻‍♀️ Question
> 맞게 짠 것인지..

## 🔗 Reference
Issue #9

2023-12-11 11:30 UTC, yooyouny commented on back/src/main/java/com/developaw/harupuppy/domain/dog/domain/Dog.java
> +  @Column(name = "weight")
@Column은 데이터베이스 컬럼 설정과 관련있는데 다른 이름이 아니라면 굳이 명시하지 않아도 jpa에서 동일하게 만들어줍니다

2023-12-11 11:30 UTC, yooyouny commented on back/src/main/java/com/developaw/harupuppy/domain/dog/domain/Dog.java
> +  private LocalDateTime birthday;
생년월일까지만 저장해도 되지않을까요? 시간까지 굳이 지정하지 않아도 될 것 같습니다

2023-12-11 11:33 UTC, yooyouny commented on back/src/main/java/com/developaw/harupuppy/domain/home/domain/Home.java
> +  @Column(name = "home_id", updatable = false, nullable = false)
IDENTIFY 전략이면 DB가 알아서 만들어주는 필드인건데 해당 컬럼 설정이 필요할까요?

2023-12-11 11:34 UTC, yooyouny commented on back/src/main/java/com/developaw/harupuppy/domain/home/domain/Home.java
> +  @Column(name = "home_name", nullable = false)
저는 유효성 검증을 엔티티에도 해주고 dto에도 해주는 편인데 이걸 DB 컬럼 옵션으로 지정하기 보다는 Spring validation 어노테이션을 활용하는것이 좋지 않을까 싶습니다

2023-12-11 11:36 UTC, yooyouny commented on back/src/main/java/com/developaw/harupuppy/domain/dog/domain/Dog.java
> +  @CreatedDate
생성일 수정일 같이 엔티티에 공통적으로 들어가는 필드는 따로 클래스를 만들어서 상속받아 쓰곤합니다 제가 만든거에 추가되어있으니 나중에 참고하셔서 수정하면 될 것 같습니다

2023-12-11 11:38 UTC, yooyouny commented on back/src/main/java/com/developaw/harupuppy/domain/user/domain/User.java
> +  @Column(name = "is_deleted", nullable = false, columnDefinition = "TINYINT(1)")
boolean 타입은 기본형이라 애초에 null을 허용하지 않기 떄문에 nullable을 체크하지 않아도 되는거 아닐까요?

2023-12-11 11:44 UTC, yooyouny commented on back/src/main/java/com/developaw/harupuppy/domain/user/domain/User.java
> +  public User(String userImg, String nickname, UserRole userRole) {
유저를 생성하는데 3개의 필드에만 값을 넣어주면 나머지 객체엔 값을 언제 넣어주나요?  마찬가지로 Home 필드에 연관관계를 만들어줄때 Home에 있는 List<User>에는 언제 User를 추가해주나요?

2023-12-11 11:46 UTC, yooyouny commented on back/src/main/java/com/developaw/harupuppy/domain/dog/domain/Dog.java
> +  @Column(name = "name", nullable = false)
String이 널체크만 하면 되는걸까요?

2023-12-11 11:53 UTC, yooyouny commented on back/src/main/java/com/developaw/harupuppy/domain/user/domain/User.java
> +  @ManyToOne
유저를 조회할때 연관된 엔티티들도 즉각적으로 가져와야한다고 생각하셔서 이렇게 작성하신 걸까요?

2023-12-11 11:55 UTC, yooyouny commented on back/src/main/java/com/developaw/harupuppy/domain/home/domain/Home.java
> +public class Home {
생성자가 기본생성자밖에 없네요

2023-12-11 12:12 UTC, yooyouny requested changes
작성하신 분이 무슨 의도로 어떤 생각을 가지고 작성하신건지를 알아야 리뷰가 제대로 될 것 같은데 올려주신 내용에는 그런 부분이 전혀 드러나있지가 않습니다 템플릿으로 만들어놓기까지 했는데 성의있게 채워주셨으면 합니다 

모든 객체에 공통적으로 보이는 것들이 있는데 코멘트는 한곳에만 달았습니다 
- 객체와 객체간의 연관관계를 정의해주셨는데 생성할때 해당 필드들을 전혀 넣어주고 있지가 않습니다
- 거의 모든 필드에 nullable이 남발되어있는것 같은데 null확인이 필요한 타입인지 아닌지, @NotNull과 @Column(nullable=false)를 구분하셨으면 좋겠습니다 
- 제가 ERD 만들기도 전에 JPA 특정 부분은 보셨으면 좋겠다고 카테고리를 짚어드렸는데 지금 코드만 봐서는 해당 부분이 제대로 인지되었는지 의문입니다.. 지연로딩과 N+1문제를 함께 봐보시고 수정에 반영해주셨으면 합니다

2023-12-11 12:31 UTC, senique-dev commented on back/src/main/java/com/developaw/harupuppy/domain/dog/domain/Dog.java
> +  @Column(name = "weight")
넵 그럼 변수이름이랑 다른거 빼고는 그냥 안적어도 되겠네요!

2023-12-11 12:32 UTC, senique-dev commented on back/src/main/java/com/developaw/harupuppy/domain/dog/domain/Dog.java
> +  private LocalDateTime birthday;
그렇네요, 로컬데이트로 수정하겠습니다

2023-12-11 12:44 UTC, senique-dev commented on back/src/main/java/com/developaw/harupuppy/domain/home/domain/Home.java
> +  @Column(name = "home_id", updatable = false, nullable = false)
필요없겠네요...!

2023-12-11 18:04 UTC, merged

2023-12-13 03:18 UTC, senique-dev commented on back/src/main/java/com/developaw/harupuppy/domain/user/domain/User.java
> +  @Column(name = "is_deleted", nullable = false, columnDefinition = "TINYINT(1)")
네, 말씀이 맞는것 같아요.

2023-12-13 03:19 UTC, senique-dev commented on back/src/main/java/com/developaw/harupuppy/domain/user/domain/User.java
> +  @ManyToOne
지연로딩에 대해서 알아보긴 했는데 코드에 어떻게 적용시켜야 할지는 더 찾아봐야 할 것 같습니다.

2023-12-13 03:20 UTC, senique-dev commented on back/src/main/java/com/developaw/harupuppy/domain/dog/domain/Dog.java
> +  @Column(name = "name", nullable = false)
잘모르겠습니다,,!

2023-12-13 03:20 UTC, senique-dev commented on back/src/main/java/com/developaw/harupuppy/domain/user/domain/User.java
> +  public User(String userImg, String nickname, UserRole userRole) {
수정해봤는데 맞는지는 모르겠습니다. 추가로 알아볼예정입니다.

2023-12-13 03:21 UTC, senique-dev commented on back/src/main/java/com/developaw/harupuppy/domain/home/domain/Home.java
> +public class Home {
이것도 다시 알아보겠습니다.