Design/88 setting page UI
coding-union-kr/haru-puppy pull request #98
Opened 2024-01-07 14:38 UTC by junmieee

## ✅ Changes Made
- setting 페이지 UI
- 알림 설정 토글시 함수 추가 
- 로그아웃 클릭 시 모달창 & 모달창의 '로그아웃'버튼 클릭시 로그아웃 함수 추가
- 회원탈퇴 모달창 & 모달의 '회원 탈퇴' 클릭시 회원탈퇴 api 요청 
- 메이트 초대하기 클릭 시 /setting/userprofile 로 라우팅 설정
- /setting/userprofile 페이지 UI & 함수 기능 

## 🙋🏻‍ Review Point
- 모달창이 나타났을 때 아래 스크린샷과 같이 top과 bottom nav가 overlay 적용에서 제외된 것 같아서 z-index: 100; 요고 추가했습니다. 확인 부탁드려요 
- Topnav에서 pathname 설정하는 함수에서 case에 /setting/userprofile 추가했습니다. 확인 부탁드립니다. 
- 코드가 너무 길어지는 것 같아서 다음주에 리프레시 토큰 로직 할 때 interceptor 만드면서  axios 모듈도 함께 분리하도록 하겠습니다.

## 📸 Screenshot
> 

설정 페이지 UI
<img width="397" alt="스크린샷 2024-01-07 오후 5 48 04" src="https://github.com/coding-union-kr/haru-puppy/assets/76501504/1952e542-45b3-4d60-aec1-84125ffa1af5">

모달창 z-index 적용 전
<img width="397" alt="스크린샷 2024-01-07 오후 5 47 05" src="https://github.com/coding-union-kr/haru-puppy/assets/76501504/f0ae1c7f-fa9d-4a52-8631-a287d6ad51c6">

/setting/userprofile 페이지
![스크린샷 2024-01-07 오후 11 35 32](https://github.com/coding-union-kr/haru-puppy/assets/76501504/92fa106c-c968-4f29-b3d9-96daacff6456)

## 🙋🏻‍♀️ Question
> 
 NavMenu에서 코드는 바뀐게 없는데 스페이스들?이 변경점으로 들어간것같아요....혹시 이거 머지될 때 충돌 일어나진 않을까요?

/setting/userprofile 페이지에서 role 부분 input이 스크린 샷에서 보는 것 처럼 잘려서 나옵니다... 왜그럴까용? 필요한 props들 다 넘겨주고 타입에러도 안나고 있는데..흠 /auth/userprofile에서도 똑같은 현상이였던 것 같은데 곰곰님은 혹시 제대로 보이시나요?

## 🔗 Reference
Issue #88

2024-01-07 19:22 UTC, CosmicLatte009 requested changes
RoleDropDown UI가 왜 안나오는지 코멘트 달긴했지만 세팅 페이지에서 들어가는 유저 프로필 수정 페이지는 /profile/my 페이지로 라우트하면 될거라고 생각했는데요..! 
/setting 이 url 에 들어가는 편이 더 적합하다고 생각하셔서 /setting/userprofile 에 페이지를 만드신건가여?

2024-01-07 19:22 UTC, CosmicLatte009 commented on front/app/(route)/setting/userprofile/page.tsx
> +        role: '',
RoleDropdown에서 기본값이 설정되어있지 않아서 UI에서 안 보이는거에융.
해당 부분은 /auth/register/user 페이지 코드 17~22번째줄 참고하시면 될 것 같아여!
formData의 name도 백엔드로 요청보내려면 imgUrl, nickName, userRole로 바뀌어야할거에요!

2024-01-07 19:22 UTC, CosmicLatte009 commented on front/app/(route)/setting/userprofile/page.tsx
> +            queryClient.invalidateQueries('userProfile');
옹...이 새로운 react-query 문법 뭔가용..? queryClient에 기본으로 있는 기능인가여? 안 쓰는거랑 어떻게 다르게 좋은가융? 👀

2024-01-07 19:22 UTC, CosmicLatte009 commented on front/app/(route)/setting/page.tsx
> +                            btn1="취소"
UI적으로 취소버튼이 오른쪽으로 가는걸 더 많이 본 것 같아서 btn1과 btn2가 바뀌는건 어떨까 제안드려봅니당. 급한건 아니니 나중에 정해도 될 것 같지만융!

2024-01-08 01:53 UTC, junmieee commented
> RoleDropDown UI가 왜 안나오는지 코멘트 달긴했지만 세팅 페이지에서 들어가는 유저 프로필 수정 페이지는 /profile/my 페이지로 라우트하면 될거라고 생각했는데요..! /setting 이 url 에 들어가는 편이 더 적합하다고 생각하셔서 /setting/userprofile 에 페이지를 만드신건가여?

엇 맞아요 profile/my를 미리 만들어놨었군욧....허허 그럼 setting/userprofile 경로 없애고 이 코드를 profile/my 로 옮길게용 ㅎㅎ

2024-01-08 01:59 UTC, junmieee commented on front/app/(route)/setting/userprofile/page.tsx
> +            queryClient.invalidateQueries('userProfile');
> 옹...이 새로운 react-query 문법 뭔가용..? queryClient에 기본으로 있는 기능인가여? 안 쓰는거랑 어떻게 다르게 좋은가융? 👀

수정 api요청을 보냈을 때 받아오는 데이터 값은 따로 없으니깐 리액트 쿼리에서 'userProfile' 키값을 가진 쿼리의 캐시 데이터를 업데이트 해주는 기능이에요. 서버랑 클라이언트 데이터 동기화?해주는 거라고 알고있어요.

2024-01-08 02:52 UTC, junmieee commented on front/app/(route)/setting/page.tsx
> +                            btn1="취소"
> UI적으로 취소버튼이 오른쪽으로 가는걸 더 많이 본 것 같아서 btn1과 btn2가 바뀌는건 어떨까 제안드려봅니당. 급한건 아니니 나중에 정해도 될 것 같지만융!

오 저는 왼쪽인줄 알았는데 오른쪽에 가는 경우가 많군요...이 부분은 좀 더 레퍼런스 찾아보고 나중에 다시 수정하도록 하죠

2024-01-09 05:22 UTC, merged